<?php
function module_vishal_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the block module.
    case 'help.module_vishal':
      return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href=":blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.') . '</p>';
}}

 function module_vishal_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $query = \Drupal::database()->query('SELECT * FROM node_field_data');
    $a = $query->fetchAll();
    // print_rs($a);
    // Drupal::logger("efef")->info("efefef");
    // $current_user = \Drupal::currentUser();
    // dump($current_user->hasPermission('access content'));

  if($form_id == "node_article_form"){
    $form["field_image"]["widget"]["#field_name"] = "vishal";

  }   
}
function module_vishal_theme( ){

  return [
    "vishal" => ["variables" => [
      "items" => [],"title" => ""
     ] 
    ],
    
    "tabless" => ["variables" => [
      "con" => []
  ]
  ]
  ];
  }

/**
* Provides a Feature News block.
*
* @Block(
* id = "learning_featurenews",
* admin_label = @Translation("Feature News"),
* category = @Translation("Custom")
* )
*/ 
